A-BST-Grows-In-Brooklyn/graceShopper

README.md, package-lock.json, package.json, public/index.html
=> Local port

server/db/models/cart.js
=> initial cart model created

client/components/AllSlimes.js, client/components/SingleSlime.js, client/components/Slime.js, client/components/index.js, client/routes.js, client/store/index.js, client/store/slime.js, client/store/slime.spec.js, server/api/index.js, server/api/slimes.js, server/api/slimes.spec.js, server/db/models/index.js, server/db/models/slime.js
Implementation Details:
- Add Express route to get all available products
- Add sub-reducer that includes products as an array in state
- Add a React component to display all products
- Make my products model
- Add express route to get single product
- Add sub-reducer to add single product to state
- Create a React component to display single product, include a button for 'add-to-cart' (no functionality for now)
- Added api route test for GET all slimes
- Add thunk creator test for GET all slimes
Closes #3 
Closes #6
=> #3 and #6: all products / single products

package-lock.json, package.json, script/oldSeed.js, script/seed.js, server/db/models/cart.js, server/db/models/index.js, server/db/models/user.js
=> eed file added + working

server/api/slimes.js
- POST and DELETE routes for admin
=> eod-post-delete-admin-routes

client/components/Home.js, client/components/index.js, client/components/navbar.js, client/routes.js, package-lock.json, package.json, public/style.css
=> React components hooked up and buttons added

client/components/SingleSlime.js, client/components/Slime.js
=> pictures showing!

client/components/SingleSlime.js, client/components/cart.js, client/components/navbar.js, client/store/cart.js, public/style.css, server/api/cart.js
=> Edit cart quant

client/components/SingleSlime.js, client/components/navbar.js, client/store/cart.js, server/api/cart.js
=> add to cart working :3

server/api/slimes.js, server/api/users.js, server/db/models/slime.spec.js
- slime test
- admin access api routes
=> slime test+admin access

client/store/cart.js, script/seed.js
=> old seed restored

client/components/navbar.js, client/routes.js, client/store/cart.js, server/api/slimes.js
=> New master branch

client/routes.js
=> fix: navigation to homepage when logged in

script/seed.js
Working seed file using faker.
=> refactor: seed file using faker

client/components/cart.js, public/style.css, server/db/models/line-item.js, server/db/models/order.js, server/db/models/slime.js
=> chore: create newDatabase structures

server/api/users.js
- added get single user by id on backend for admin view
=> view single user by id

client/components/user-home.js, client/routes.js
=> fix: routes and user-home component updated

server/db/models/lineItem.js, server/db/models/lineItem.spec.js, server/db/models/order.js, utilityFunctions.js
=> Chore: update order update item in database

server/api/cart.js, server/db/models/index.js, server/db/models/lineItem.js, server/index.js
=> chore: view cart and add to cart working!!!

client/components/cart.spec.js, server/api/cart.spec.js, server/db/models/lineItem.spec.js, server/db/models/order.js, server/index.js
=> chore: guest cart db hooks done + tests working
